// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExperimentModel.proto

package eu.recap.sim.models;

public final class ExperimentModel {
  private ExperimentModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExperimentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:models.Experiment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string Name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double Duration = 2;</code>
     */
    double getDuration();

    /**
     * <code>string PlacementPolicy = 3;</code>
     */
    java.lang.String getPlacementPolicy();
    /**
     * <code>string PlacementPolicy = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlacementPolicyBytes();

    /**
     * <code>string ConsolidationPolicy = 4;</code>
     */
    java.lang.String getConsolidationPolicy();
    /**
     * <code>string ConsolidationPolicy = 4;</code>
     */
    com.google.protobuf.ByteString
        getConsolidationPolicyBytes();

    /**
     * <code>string AutoScalinigPolicy = 5;</code>
     */
    java.lang.String getAutoScalinigPolicy();
    /**
     * <code>string AutoScalinigPolicy = 5;</code>
     */
    com.google.protobuf.ByteString
        getAutoScalinigPolicyBytes();

    /**
     * <code>string RequestRoutingPolicy = 6;</code>
     */
    java.lang.String getRequestRoutingPolicy();
    /**
     * <code>string RequestRoutingPolicy = 6;</code>
     */
    com.google.protobuf.ByteString
        getRequestRoutingPolicyBytes();

    /**
     * <code>.models.Infrastructure infrastructure = 7;</code>
     */
    boolean hasInfrastructure();
    /**
     * <code>.models.Infrastructure infrastructure = 7;</code>
     */
    eu.recap.sim.models.InfrastructureModel.Infrastructure getInfrastructure();
    /**
     * <code>.models.Infrastructure infrastructure = 7;</code>
     */
    eu.recap.sim.models.InfrastructureModel.InfrastructureOrBuilder getInfrastructureOrBuilder();

    /**
     * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
     */
    boolean hasApplicationLandscape();
    /**
     * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
     */
    eu.recap.sim.models.ApplicationModel.ApplicationLandscape getApplicationLandscape();
    /**
     * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
     */
    eu.recap.sim.models.ApplicationModel.ApplicationLandscapeOrBuilder getApplicationLandscapeOrBuilder();

    /**
     * <code>.models.Workload workload = 9;</code>
     */
    boolean hasWorkload();
    /**
     * <code>.models.Workload workload = 9;</code>
     */
    eu.recap.sim.models.WorkloadModel.Workload getWorkload();
    /**
     * <code>.models.Workload workload = 9;</code>
     */
    eu.recap.sim.models.WorkloadModel.WorkloadOrBuilder getWorkloadOrBuilder();
  }
  /**
   * Protobuf type {@code models.Experiment}
   */
  public  static final class Experiment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:models.Experiment)
      ExperimentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Experiment.newBuilder() to construct.
    private Experiment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Experiment() {
      name_ = "";
      placementPolicy_ = "";
      consolidationPolicy_ = "";
      autoScalinigPolicy_ = "";
      requestRoutingPolicy_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Experiment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 17: {

              duration_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              placementPolicy_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              consolidationPolicy_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              autoScalinigPolicy_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              requestRoutingPolicy_ = s;
              break;
            }
            case 58: {
              eu.recap.sim.models.InfrastructureModel.Infrastructure.Builder subBuilder = null;
              if (infrastructure_ != null) {
                subBuilder = infrastructure_.toBuilder();
              }
              infrastructure_ = input.readMessage(eu.recap.sim.models.InfrastructureModel.Infrastructure.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(infrastructure_);
                infrastructure_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              eu.recap.sim.models.ApplicationModel.ApplicationLandscape.Builder subBuilder = null;
              if (applicationLandscape_ != null) {
                subBuilder = applicationLandscape_.toBuilder();
              }
              applicationLandscape_ = input.readMessage(eu.recap.sim.models.ApplicationModel.ApplicationLandscape.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(applicationLandscape_);
                applicationLandscape_ = subBuilder.buildPartial();
              }

              break;
            }
            case 74: {
              eu.recap.sim.models.WorkloadModel.Workload.Builder subBuilder = null;
              if (workload_ != null) {
                subBuilder = workload_.toBuilder();
              }
              workload_ = input.readMessage(eu.recap.sim.models.WorkloadModel.Workload.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(workload_);
                workload_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.recap.sim.models.ExperimentModel.internal_static_models_Experiment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.recap.sim.models.ExperimentModel.internal_static_models_Experiment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.recap.sim.models.ExperimentModel.Experiment.class, eu.recap.sim.models.ExperimentModel.Experiment.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string Name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string Name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 2;
    private double duration_;
    /**
     * <code>double Duration = 2;</code>
     */
    public double getDuration() {
      return duration_;
    }

    public static final int PLACEMENTPOLICY_FIELD_NUMBER = 3;
    private volatile java.lang.Object placementPolicy_;
    /**
     * <code>string PlacementPolicy = 3;</code>
     */
    public java.lang.String getPlacementPolicy() {
      java.lang.Object ref = placementPolicy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        placementPolicy_ = s;
        return s;
      }
    }
    /**
     * <code>string PlacementPolicy = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlacementPolicyBytes() {
      java.lang.Object ref = placementPolicy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        placementPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSOLIDATIONPOLICY_FIELD_NUMBER = 4;
    private volatile java.lang.Object consolidationPolicy_;
    /**
     * <code>string ConsolidationPolicy = 4;</code>
     */
    public java.lang.String getConsolidationPolicy() {
      java.lang.Object ref = consolidationPolicy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consolidationPolicy_ = s;
        return s;
      }
    }
    /**
     * <code>string ConsolidationPolicy = 4;</code>
     */
    public com.google.protobuf.ByteString
        getConsolidationPolicyBytes() {
      java.lang.Object ref = consolidationPolicy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consolidationPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTOSCALINIGPOLICY_FIELD_NUMBER = 5;
    private volatile java.lang.Object autoScalinigPolicy_;
    /**
     * <code>string AutoScalinigPolicy = 5;</code>
     */
    public java.lang.String getAutoScalinigPolicy() {
      java.lang.Object ref = autoScalinigPolicy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        autoScalinigPolicy_ = s;
        return s;
      }
    }
    /**
     * <code>string AutoScalinigPolicy = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAutoScalinigPolicyBytes() {
      java.lang.Object ref = autoScalinigPolicy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autoScalinigPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTROUTINGPOLICY_FIELD_NUMBER = 6;
    private volatile java.lang.Object requestRoutingPolicy_;
    /**
     * <code>string RequestRoutingPolicy = 6;</code>
     */
    public java.lang.String getRequestRoutingPolicy() {
      java.lang.Object ref = requestRoutingPolicy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestRoutingPolicy_ = s;
        return s;
      }
    }
    /**
     * <code>string RequestRoutingPolicy = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRequestRoutingPolicyBytes() {
      java.lang.Object ref = requestRoutingPolicy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestRoutingPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFRASTRUCTURE_FIELD_NUMBER = 7;
    private eu.recap.sim.models.InfrastructureModel.Infrastructure infrastructure_;
    /**
     * <code>.models.Infrastructure infrastructure = 7;</code>
     */
    public boolean hasInfrastructure() {
      return infrastructure_ != null;
    }
    /**
     * <code>.models.Infrastructure infrastructure = 7;</code>
     */
    public eu.recap.sim.models.InfrastructureModel.Infrastructure getInfrastructure() {
      return infrastructure_ == null ? eu.recap.sim.models.InfrastructureModel.Infrastructure.getDefaultInstance() : infrastructure_;
    }
    /**
     * <code>.models.Infrastructure infrastructure = 7;</code>
     */
    public eu.recap.sim.models.InfrastructureModel.InfrastructureOrBuilder getInfrastructureOrBuilder() {
      return getInfrastructure();
    }

    public static final int APPLICATIONLANDSCAPE_FIELD_NUMBER = 8;
    private eu.recap.sim.models.ApplicationModel.ApplicationLandscape applicationLandscape_;
    /**
     * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
     */
    public boolean hasApplicationLandscape() {
      return applicationLandscape_ != null;
    }
    /**
     * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
     */
    public eu.recap.sim.models.ApplicationModel.ApplicationLandscape getApplicationLandscape() {
      return applicationLandscape_ == null ? eu.recap.sim.models.ApplicationModel.ApplicationLandscape.getDefaultInstance() : applicationLandscape_;
    }
    /**
     * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
     */
    public eu.recap.sim.models.ApplicationModel.ApplicationLandscapeOrBuilder getApplicationLandscapeOrBuilder() {
      return getApplicationLandscape();
    }

    public static final int WORKLOAD_FIELD_NUMBER = 9;
    private eu.recap.sim.models.WorkloadModel.Workload workload_;
    /**
     * <code>.models.Workload workload = 9;</code>
     */
    public boolean hasWorkload() {
      return workload_ != null;
    }
    /**
     * <code>.models.Workload workload = 9;</code>
     */
    public eu.recap.sim.models.WorkloadModel.Workload getWorkload() {
      return workload_ == null ? eu.recap.sim.models.WorkloadModel.Workload.getDefaultInstance() : workload_;
    }
    /**
     * <code>.models.Workload workload = 9;</code>
     */
    public eu.recap.sim.models.WorkloadModel.WorkloadOrBuilder getWorkloadOrBuilder() {
      return getWorkload();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (duration_ != 0D) {
        output.writeDouble(2, duration_);
      }
      if (!getPlacementPolicyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, placementPolicy_);
      }
      if (!getConsolidationPolicyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, consolidationPolicy_);
      }
      if (!getAutoScalinigPolicyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, autoScalinigPolicy_);
      }
      if (!getRequestRoutingPolicyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requestRoutingPolicy_);
      }
      if (infrastructure_ != null) {
        output.writeMessage(7, getInfrastructure());
      }
      if (applicationLandscape_ != null) {
        output.writeMessage(8, getApplicationLandscape());
      }
      if (workload_ != null) {
        output.writeMessage(9, getWorkload());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (duration_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, duration_);
      }
      if (!getPlacementPolicyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, placementPolicy_);
      }
      if (!getConsolidationPolicyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, consolidationPolicy_);
      }
      if (!getAutoScalinigPolicyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, autoScalinigPolicy_);
      }
      if (!getRequestRoutingPolicyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requestRoutingPolicy_);
      }
      if (infrastructure_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getInfrastructure());
      }
      if (applicationLandscape_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getApplicationLandscape());
      }
      if (workload_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getWorkload());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eu.recap.sim.models.ExperimentModel.Experiment)) {
        return super.equals(obj);
      }
      eu.recap.sim.models.ExperimentModel.Experiment other = (eu.recap.sim.models.ExperimentModel.Experiment) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Double.doubleToLongBits(getDuration())
          != java.lang.Double.doubleToLongBits(
              other.getDuration())) return false;
      if (!getPlacementPolicy()
          .equals(other.getPlacementPolicy())) return false;
      if (!getConsolidationPolicy()
          .equals(other.getConsolidationPolicy())) return false;
      if (!getAutoScalinigPolicy()
          .equals(other.getAutoScalinigPolicy())) return false;
      if (!getRequestRoutingPolicy()
          .equals(other.getRequestRoutingPolicy())) return false;
      if (hasInfrastructure() != other.hasInfrastructure()) return false;
      if (hasInfrastructure()) {
        if (!getInfrastructure()
            .equals(other.getInfrastructure())) return false;
      }
      if (hasApplicationLandscape() != other.hasApplicationLandscape()) return false;
      if (hasApplicationLandscape()) {
        if (!getApplicationLandscape()
            .equals(other.getApplicationLandscape())) return false;
      }
      if (hasWorkload() != other.hasWorkload()) return false;
      if (hasWorkload()) {
        if (!getWorkload()
            .equals(other.getWorkload())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDuration()));
      hash = (37 * hash) + PLACEMENTPOLICY_FIELD_NUMBER;
      hash = (53 * hash) + getPlacementPolicy().hashCode();
      hash = (37 * hash) + CONSOLIDATIONPOLICY_FIELD_NUMBER;
      hash = (53 * hash) + getConsolidationPolicy().hashCode();
      hash = (37 * hash) + AUTOSCALINIGPOLICY_FIELD_NUMBER;
      hash = (53 * hash) + getAutoScalinigPolicy().hashCode();
      hash = (37 * hash) + REQUESTROUTINGPOLICY_FIELD_NUMBER;
      hash = (53 * hash) + getRequestRoutingPolicy().hashCode();
      if (hasInfrastructure()) {
        hash = (37 * hash) + INFRASTRUCTURE_FIELD_NUMBER;
        hash = (53 * hash) + getInfrastructure().hashCode();
      }
      if (hasApplicationLandscape()) {
        hash = (37 * hash) + APPLICATIONLANDSCAPE_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationLandscape().hashCode();
      }
      if (hasWorkload()) {
        hash = (37 * hash) + WORKLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getWorkload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eu.recap.sim.models.ExperimentModel.Experiment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eu.recap.sim.models.ExperimentModel.Experiment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code models.Experiment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:models.Experiment)
        eu.recap.sim.models.ExperimentModel.ExperimentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.recap.sim.models.ExperimentModel.internal_static_models_Experiment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.recap.sim.models.ExperimentModel.internal_static_models_Experiment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.recap.sim.models.ExperimentModel.Experiment.class, eu.recap.sim.models.ExperimentModel.Experiment.Builder.class);
      }

      // Construct using eu.recap.sim.models.ExperimentModel.Experiment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        duration_ = 0D;

        placementPolicy_ = "";

        consolidationPolicy_ = "";

        autoScalinigPolicy_ = "";

        requestRoutingPolicy_ = "";

        if (infrastructureBuilder_ == null) {
          infrastructure_ = null;
        } else {
          infrastructure_ = null;
          infrastructureBuilder_ = null;
        }
        if (applicationLandscapeBuilder_ == null) {
          applicationLandscape_ = null;
        } else {
          applicationLandscape_ = null;
          applicationLandscapeBuilder_ = null;
        }
        if (workloadBuilder_ == null) {
          workload_ = null;
        } else {
          workload_ = null;
          workloadBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.recap.sim.models.ExperimentModel.internal_static_models_Experiment_descriptor;
      }

      @java.lang.Override
      public eu.recap.sim.models.ExperimentModel.Experiment getDefaultInstanceForType() {
        return eu.recap.sim.models.ExperimentModel.Experiment.getDefaultInstance();
      }

      @java.lang.Override
      public eu.recap.sim.models.ExperimentModel.Experiment build() {
        eu.recap.sim.models.ExperimentModel.Experiment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eu.recap.sim.models.ExperimentModel.Experiment buildPartial() {
        eu.recap.sim.models.ExperimentModel.Experiment result = new eu.recap.sim.models.ExperimentModel.Experiment(this);
        result.name_ = name_;
        result.duration_ = duration_;
        result.placementPolicy_ = placementPolicy_;
        result.consolidationPolicy_ = consolidationPolicy_;
        result.autoScalinigPolicy_ = autoScalinigPolicy_;
        result.requestRoutingPolicy_ = requestRoutingPolicy_;
        if (infrastructureBuilder_ == null) {
          result.infrastructure_ = infrastructure_;
        } else {
          result.infrastructure_ = infrastructureBuilder_.build();
        }
        if (applicationLandscapeBuilder_ == null) {
          result.applicationLandscape_ = applicationLandscape_;
        } else {
          result.applicationLandscape_ = applicationLandscapeBuilder_.build();
        }
        if (workloadBuilder_ == null) {
          result.workload_ = workload_;
        } else {
          result.workload_ = workloadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.recap.sim.models.ExperimentModel.Experiment) {
          return mergeFrom((eu.recap.sim.models.ExperimentModel.Experiment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.recap.sim.models.ExperimentModel.Experiment other) {
        if (other == eu.recap.sim.models.ExperimentModel.Experiment.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getDuration() != 0D) {
          setDuration(other.getDuration());
        }
        if (!other.getPlacementPolicy().isEmpty()) {
          placementPolicy_ = other.placementPolicy_;
          onChanged();
        }
        if (!other.getConsolidationPolicy().isEmpty()) {
          consolidationPolicy_ = other.consolidationPolicy_;
          onChanged();
        }
        if (!other.getAutoScalinigPolicy().isEmpty()) {
          autoScalinigPolicy_ = other.autoScalinigPolicy_;
          onChanged();
        }
        if (!other.getRequestRoutingPolicy().isEmpty()) {
          requestRoutingPolicy_ = other.requestRoutingPolicy_;
          onChanged();
        }
        if (other.hasInfrastructure()) {
          mergeInfrastructure(other.getInfrastructure());
        }
        if (other.hasApplicationLandscape()) {
          mergeApplicationLandscape(other.getApplicationLandscape());
        }
        if (other.hasWorkload()) {
          mergeWorkload(other.getWorkload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.recap.sim.models.ExperimentModel.Experiment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.recap.sim.models.ExperimentModel.Experiment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string Name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string Name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double duration_ ;
      /**
       * <code>double Duration = 2;</code>
       */
      public double getDuration() {
        return duration_;
      }
      /**
       * <code>double Duration = 2;</code>
       */
      public Builder setDuration(double value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Duration = 2;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object placementPolicy_ = "";
      /**
       * <code>string PlacementPolicy = 3;</code>
       */
      public java.lang.String getPlacementPolicy() {
        java.lang.Object ref = placementPolicy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          placementPolicy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string PlacementPolicy = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlacementPolicyBytes() {
        java.lang.Object ref = placementPolicy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          placementPolicy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string PlacementPolicy = 3;</code>
       */
      public Builder setPlacementPolicy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        placementPolicy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string PlacementPolicy = 3;</code>
       */
      public Builder clearPlacementPolicy() {
        
        placementPolicy_ = getDefaultInstance().getPlacementPolicy();
        onChanged();
        return this;
      }
      /**
       * <code>string PlacementPolicy = 3;</code>
       */
      public Builder setPlacementPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        placementPolicy_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object consolidationPolicy_ = "";
      /**
       * <code>string ConsolidationPolicy = 4;</code>
       */
      public java.lang.String getConsolidationPolicy() {
        java.lang.Object ref = consolidationPolicy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          consolidationPolicy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ConsolidationPolicy = 4;</code>
       */
      public com.google.protobuf.ByteString
          getConsolidationPolicyBytes() {
        java.lang.Object ref = consolidationPolicy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consolidationPolicy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ConsolidationPolicy = 4;</code>
       */
      public Builder setConsolidationPolicy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consolidationPolicy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ConsolidationPolicy = 4;</code>
       */
      public Builder clearConsolidationPolicy() {
        
        consolidationPolicy_ = getDefaultInstance().getConsolidationPolicy();
        onChanged();
        return this;
      }
      /**
       * <code>string ConsolidationPolicy = 4;</code>
       */
      public Builder setConsolidationPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        consolidationPolicy_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object autoScalinigPolicy_ = "";
      /**
       * <code>string AutoScalinigPolicy = 5;</code>
       */
      public java.lang.String getAutoScalinigPolicy() {
        java.lang.Object ref = autoScalinigPolicy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          autoScalinigPolicy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string AutoScalinigPolicy = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAutoScalinigPolicyBytes() {
        java.lang.Object ref = autoScalinigPolicy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          autoScalinigPolicy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string AutoScalinigPolicy = 5;</code>
       */
      public Builder setAutoScalinigPolicy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        autoScalinigPolicy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string AutoScalinigPolicy = 5;</code>
       */
      public Builder clearAutoScalinigPolicy() {
        
        autoScalinigPolicy_ = getDefaultInstance().getAutoScalinigPolicy();
        onChanged();
        return this;
      }
      /**
       * <code>string AutoScalinigPolicy = 5;</code>
       */
      public Builder setAutoScalinigPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        autoScalinigPolicy_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestRoutingPolicy_ = "";
      /**
       * <code>string RequestRoutingPolicy = 6;</code>
       */
      public java.lang.String getRequestRoutingPolicy() {
        java.lang.Object ref = requestRoutingPolicy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestRoutingPolicy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RequestRoutingPolicy = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRequestRoutingPolicyBytes() {
        java.lang.Object ref = requestRoutingPolicy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestRoutingPolicy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RequestRoutingPolicy = 6;</code>
       */
      public Builder setRequestRoutingPolicy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestRoutingPolicy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RequestRoutingPolicy = 6;</code>
       */
      public Builder clearRequestRoutingPolicy() {
        
        requestRoutingPolicy_ = getDefaultInstance().getRequestRoutingPolicy();
        onChanged();
        return this;
      }
      /**
       * <code>string RequestRoutingPolicy = 6;</code>
       */
      public Builder setRequestRoutingPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestRoutingPolicy_ = value;
        onChanged();
        return this;
      }

      private eu.recap.sim.models.InfrastructureModel.Infrastructure infrastructure_;
      private com.google.protobuf.SingleFieldBuilderV3<
          eu.recap.sim.models.InfrastructureModel.Infrastructure, eu.recap.sim.models.InfrastructureModel.Infrastructure.Builder, eu.recap.sim.models.InfrastructureModel.InfrastructureOrBuilder> infrastructureBuilder_;
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public boolean hasInfrastructure() {
        return infrastructureBuilder_ != null || infrastructure_ != null;
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public eu.recap.sim.models.InfrastructureModel.Infrastructure getInfrastructure() {
        if (infrastructureBuilder_ == null) {
          return infrastructure_ == null ? eu.recap.sim.models.InfrastructureModel.Infrastructure.getDefaultInstance() : infrastructure_;
        } else {
          return infrastructureBuilder_.getMessage();
        }
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public Builder setInfrastructure(eu.recap.sim.models.InfrastructureModel.Infrastructure value) {
        if (infrastructureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          infrastructure_ = value;
          onChanged();
        } else {
          infrastructureBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public Builder setInfrastructure(
          eu.recap.sim.models.InfrastructureModel.Infrastructure.Builder builderForValue) {
        if (infrastructureBuilder_ == null) {
          infrastructure_ = builderForValue.build();
          onChanged();
        } else {
          infrastructureBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public Builder mergeInfrastructure(eu.recap.sim.models.InfrastructureModel.Infrastructure value) {
        if (infrastructureBuilder_ == null) {
          if (infrastructure_ != null) {
            infrastructure_ =
              eu.recap.sim.models.InfrastructureModel.Infrastructure.newBuilder(infrastructure_).mergeFrom(value).buildPartial();
          } else {
            infrastructure_ = value;
          }
          onChanged();
        } else {
          infrastructureBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public Builder clearInfrastructure() {
        if (infrastructureBuilder_ == null) {
          infrastructure_ = null;
          onChanged();
        } else {
          infrastructure_ = null;
          infrastructureBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public eu.recap.sim.models.InfrastructureModel.Infrastructure.Builder getInfrastructureBuilder() {
        
        onChanged();
        return getInfrastructureFieldBuilder().getBuilder();
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      public eu.recap.sim.models.InfrastructureModel.InfrastructureOrBuilder getInfrastructureOrBuilder() {
        if (infrastructureBuilder_ != null) {
          return infrastructureBuilder_.getMessageOrBuilder();
        } else {
          return infrastructure_ == null ?
              eu.recap.sim.models.InfrastructureModel.Infrastructure.getDefaultInstance() : infrastructure_;
        }
      }
      /**
       * <code>.models.Infrastructure infrastructure = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          eu.recap.sim.models.InfrastructureModel.Infrastructure, eu.recap.sim.models.InfrastructureModel.Infrastructure.Builder, eu.recap.sim.models.InfrastructureModel.InfrastructureOrBuilder> 
          getInfrastructureFieldBuilder() {
        if (infrastructureBuilder_ == null) {
          infrastructureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              eu.recap.sim.models.InfrastructureModel.Infrastructure, eu.recap.sim.models.InfrastructureModel.Infrastructure.Builder, eu.recap.sim.models.InfrastructureModel.InfrastructureOrBuilder>(
                  getInfrastructure(),
                  getParentForChildren(),
                  isClean());
          infrastructure_ = null;
        }
        return infrastructureBuilder_;
      }

      private eu.recap.sim.models.ApplicationModel.ApplicationLandscape applicationLandscape_;
      private com.google.protobuf.SingleFieldBuilderV3<
          eu.recap.sim.models.ApplicationModel.ApplicationLandscape, eu.recap.sim.models.ApplicationModel.ApplicationLandscape.Builder, eu.recap.sim.models.ApplicationModel.ApplicationLandscapeOrBuilder> applicationLandscapeBuilder_;
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public boolean hasApplicationLandscape() {
        return applicationLandscapeBuilder_ != null || applicationLandscape_ != null;
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public eu.recap.sim.models.ApplicationModel.ApplicationLandscape getApplicationLandscape() {
        if (applicationLandscapeBuilder_ == null) {
          return applicationLandscape_ == null ? eu.recap.sim.models.ApplicationModel.ApplicationLandscape.getDefaultInstance() : applicationLandscape_;
        } else {
          return applicationLandscapeBuilder_.getMessage();
        }
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public Builder setApplicationLandscape(eu.recap.sim.models.ApplicationModel.ApplicationLandscape value) {
        if (applicationLandscapeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applicationLandscape_ = value;
          onChanged();
        } else {
          applicationLandscapeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public Builder setApplicationLandscape(
          eu.recap.sim.models.ApplicationModel.ApplicationLandscape.Builder builderForValue) {
        if (applicationLandscapeBuilder_ == null) {
          applicationLandscape_ = builderForValue.build();
          onChanged();
        } else {
          applicationLandscapeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public Builder mergeApplicationLandscape(eu.recap.sim.models.ApplicationModel.ApplicationLandscape value) {
        if (applicationLandscapeBuilder_ == null) {
          if (applicationLandscape_ != null) {
            applicationLandscape_ =
              eu.recap.sim.models.ApplicationModel.ApplicationLandscape.newBuilder(applicationLandscape_).mergeFrom(value).buildPartial();
          } else {
            applicationLandscape_ = value;
          }
          onChanged();
        } else {
          applicationLandscapeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public Builder clearApplicationLandscape() {
        if (applicationLandscapeBuilder_ == null) {
          applicationLandscape_ = null;
          onChanged();
        } else {
          applicationLandscape_ = null;
          applicationLandscapeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public eu.recap.sim.models.ApplicationModel.ApplicationLandscape.Builder getApplicationLandscapeBuilder() {
        
        onChanged();
        return getApplicationLandscapeFieldBuilder().getBuilder();
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      public eu.recap.sim.models.ApplicationModel.ApplicationLandscapeOrBuilder getApplicationLandscapeOrBuilder() {
        if (applicationLandscapeBuilder_ != null) {
          return applicationLandscapeBuilder_.getMessageOrBuilder();
        } else {
          return applicationLandscape_ == null ?
              eu.recap.sim.models.ApplicationModel.ApplicationLandscape.getDefaultInstance() : applicationLandscape_;
        }
      }
      /**
       * <code>.models.ApplicationLandscape applicationLandscape = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          eu.recap.sim.models.ApplicationModel.ApplicationLandscape, eu.recap.sim.models.ApplicationModel.ApplicationLandscape.Builder, eu.recap.sim.models.ApplicationModel.ApplicationLandscapeOrBuilder> 
          getApplicationLandscapeFieldBuilder() {
        if (applicationLandscapeBuilder_ == null) {
          applicationLandscapeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              eu.recap.sim.models.ApplicationModel.ApplicationLandscape, eu.recap.sim.models.ApplicationModel.ApplicationLandscape.Builder, eu.recap.sim.models.ApplicationModel.ApplicationLandscapeOrBuilder>(
                  getApplicationLandscape(),
                  getParentForChildren(),
                  isClean());
          applicationLandscape_ = null;
        }
        return applicationLandscapeBuilder_;
      }

      private eu.recap.sim.models.WorkloadModel.Workload workload_;
      private com.google.protobuf.SingleFieldBuilderV3<
          eu.recap.sim.models.WorkloadModel.Workload, eu.recap.sim.models.WorkloadModel.Workload.Builder, eu.recap.sim.models.WorkloadModel.WorkloadOrBuilder> workloadBuilder_;
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public boolean hasWorkload() {
        return workloadBuilder_ != null || workload_ != null;
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public eu.recap.sim.models.WorkloadModel.Workload getWorkload() {
        if (workloadBuilder_ == null) {
          return workload_ == null ? eu.recap.sim.models.WorkloadModel.Workload.getDefaultInstance() : workload_;
        } else {
          return workloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public Builder setWorkload(eu.recap.sim.models.WorkloadModel.Workload value) {
        if (workloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          workload_ = value;
          onChanged();
        } else {
          workloadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public Builder setWorkload(
          eu.recap.sim.models.WorkloadModel.Workload.Builder builderForValue) {
        if (workloadBuilder_ == null) {
          workload_ = builderForValue.build();
          onChanged();
        } else {
          workloadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public Builder mergeWorkload(eu.recap.sim.models.WorkloadModel.Workload value) {
        if (workloadBuilder_ == null) {
          if (workload_ != null) {
            workload_ =
              eu.recap.sim.models.WorkloadModel.Workload.newBuilder(workload_).mergeFrom(value).buildPartial();
          } else {
            workload_ = value;
          }
          onChanged();
        } else {
          workloadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public Builder clearWorkload() {
        if (workloadBuilder_ == null) {
          workload_ = null;
          onChanged();
        } else {
          workload_ = null;
          workloadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public eu.recap.sim.models.WorkloadModel.Workload.Builder getWorkloadBuilder() {
        
        onChanged();
        return getWorkloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      public eu.recap.sim.models.WorkloadModel.WorkloadOrBuilder getWorkloadOrBuilder() {
        if (workloadBuilder_ != null) {
          return workloadBuilder_.getMessageOrBuilder();
        } else {
          return workload_ == null ?
              eu.recap.sim.models.WorkloadModel.Workload.getDefaultInstance() : workload_;
        }
      }
      /**
       * <code>.models.Workload workload = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          eu.recap.sim.models.WorkloadModel.Workload, eu.recap.sim.models.WorkloadModel.Workload.Builder, eu.recap.sim.models.WorkloadModel.WorkloadOrBuilder> 
          getWorkloadFieldBuilder() {
        if (workloadBuilder_ == null) {
          workloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              eu.recap.sim.models.WorkloadModel.Workload, eu.recap.sim.models.WorkloadModel.Workload.Builder, eu.recap.sim.models.WorkloadModel.WorkloadOrBuilder>(
                  getWorkload(),
                  getParentForChildren(),
                  isClean());
          workload_ = null;
        }
        return workloadBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:models.Experiment)
    }

    // @@protoc_insertion_point(class_scope:models.Experiment)
    private static final eu.recap.sim.models.ExperimentModel.Experiment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eu.recap.sim.models.ExperimentModel.Experiment();
    }

    public static eu.recap.sim.models.ExperimentModel.Experiment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Experiment>
        PARSER = new com.google.protobuf.AbstractParser<Experiment>() {
      @java.lang.Override
      public Experiment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Experiment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Experiment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Experiment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eu.recap.sim.models.ExperimentModel.Experiment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_Experiment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_Experiment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ExperimentModel.proto\022\006models\032\031Infrast" +
      "ructureModel.proto\032\026ApplicationModel.pro" +
      "to\032\023WorkloadModel.proto\"\254\002\n\nExperiment\022\014" +
      "\n\004Name\030\001 \001(\t\022\020\n\010Duration\030\002 \001(\001\022\027\n\017Placem" +
      "entPolicy\030\003 \001(\t\022\033\n\023ConsolidationPolicy\030\004" +
      " \001(\t\022\032\n\022AutoScalinigPolicy\030\005 \001(\t\022\034\n\024Requ" +
      "estRoutingPolicy\030\006 \001(\t\022.\n\016infrastructure" +
      "\030\007 \001(\0132\026.models.Infrastructure\022:\n\024applic" +
      "ationLandscape\030\010 \001(\0132\034.models.Applicatio" +
      "nLandscape\022\"\n\010workload\030\t \001(\0132\020.models.Wo" +
      "rkloadB&\n\023eu.recap.sim.modelsB\017Experimen" +
      "tModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          eu.recap.sim.models.InfrastructureModel.getDescriptor(),
          eu.recap.sim.models.ApplicationModel.getDescriptor(),
          eu.recap.sim.models.WorkloadModel.getDescriptor(),
        }, assigner);
    internal_static_models_Experiment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_models_Experiment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_Experiment_descriptor,
        new java.lang.String[] { "Name", "Duration", "PlacementPolicy", "ConsolidationPolicy", "AutoScalinigPolicy", "RequestRoutingPolicy", "Infrastructure", "ApplicationLandscape", "Workload", });
    eu.recap.sim.models.InfrastructureModel.getDescriptor();
    eu.recap.sim.models.ApplicationModel.getDescriptor();
    eu.recap.sim.models.WorkloadModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
