# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExperimentModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import InfrastructureModel_pb2 as InfrastructureModel__pb2
import ApplicationModel_pb2 as ApplicationModel__pb2
import WorkloadModel_pb2 as WorkloadModel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExperimentModel.proto',
  package='models',
  syntax='proto3',
  serialized_options=_b('\n\023eu.recap.sim.modelsB\017ExperimentModel'),
  serialized_pb=_b('\n\x15\x45xperimentModel.proto\x12\x06models\x1a\x19InfrastructureModel.proto\x1a\x16\x41pplicationModel.proto\x1a\x13WorkloadModel.proto\"\xac\x02\n\nExperiment\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08\x44uration\x18\x02 \x01(\x01\x12\x17\n\x0fPlacementPolicy\x18\x03 \x01(\t\x12\x1b\n\x13\x43onsolidationPolicy\x18\x04 \x01(\t\x12\x1a\n\x12\x41utoScalinigPolicy\x18\x05 \x01(\t\x12\x1c\n\x14RequestRoutingPolicy\x18\x06 \x01(\t\x12.\n\x0einfrastructure\x18\x07 \x01(\x0b\x32\x16.models.Infrastructure\x12:\n\x14\x61pplicationLandscape\x18\x08 \x01(\x0b\x32\x1c.models.ApplicationLandscape\x12\"\n\x08workload\x18\t \x01(\x0b\x32\x10.models.WorkloadB&\n\x13\x65u.recap.sim.modelsB\x0f\x45xperimentModelb\x06proto3')
  ,
  dependencies=[InfrastructureModel__pb2.DESCRIPTOR,ApplicationModel__pb2.DESCRIPTOR,WorkloadModel__pb2.DESCRIPTOR,])




_EXPERIMENT = _descriptor.Descriptor(
  name='Experiment',
  full_name='models.Experiment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Experiment.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='models.Experiment.Duration', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PlacementPolicy', full_name='models.Experiment.PlacementPolicy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ConsolidationPolicy', full_name='models.Experiment.ConsolidationPolicy', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AutoScalinigPolicy', full_name='models.Experiment.AutoScalinigPolicy', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RequestRoutingPolicy', full_name='models.Experiment.RequestRoutingPolicy', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infrastructure', full_name='models.Experiment.infrastructure', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applicationLandscape', full_name='models.Experiment.applicationLandscape', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workload', full_name='models.Experiment.workload', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=406,
)

_EXPERIMENT.fields_by_name['infrastructure'].message_type = InfrastructureModel__pb2._INFRASTRUCTURE
_EXPERIMENT.fields_by_name['applicationLandscape'].message_type = ApplicationModel__pb2._APPLICATIONLANDSCAPE
_EXPERIMENT.fields_by_name['workload'].message_type = WorkloadModel__pb2._WORKLOAD
DESCRIPTOR.message_types_by_name['Experiment'] = _EXPERIMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Experiment = _reflection.GeneratedProtocolMessageType('Experiment', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIMENT,
  __module__ = 'ExperimentModel_pb2'
  # @@protoc_insertion_point(class_scope:models.Experiment)
  ))
_sym_db.RegisterMessage(Experiment)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
