# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Utilisation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Utilisation.proto',
  package='models',
  syntax='proto3',
  serialized_options=_b('\n\023eu.recap.sim.modelsB\013Utilisation'),
  serialized_pb=_b('\n\x11Utilisation.proto\x12\x06models\"\x9c\x07\n\x0eInfrastructure\x12\x14\n\x0c\x45xperimentId\x18\x02 \x01(\t\x12\x36\n\x0b\x64\x61taCentres\x18\x01 \x03(\x0b\x32!.models.Infrastructure.DataCentre\x1a\xbb\x06\n\nDataCentre\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\n\n\x02ID\x18\x04 \x01(\t\x12\x35\n\x05nodes\x18\x01 \x03(\x0b\x32&.models.Infrastructure.DataCentre.Node\x12:\n\x08switches\x18\x02 \x03(\x0b\x32(.models.Infrastructure.DataCentre.Switch\x1a\\\n\x06Switch\x12<\n\x05links\x18\x01 \x03(\x0b\x32-.models.Infrastructure.DataCentre.Switch.Link\x1a\x14\n\x04Link\x12\x0c\n\x04Name\x18\x01 \x01(\t\x1a\xc1\x04\n\x04Node\x12\x37\n\x03\x63pu\x18\x01 \x03(\x0b\x32*.models.Infrastructure.DataCentre.Node.Cpu\x12\x45\n\nmemoryUtil\x18\x02 \x03(\x0b\x32\x31.models.Infrastructure.DataCentre.Node.MemoryUtil\x12G\n\x0bstorageUtil\x18\x03 \x03(\x0b\x32\x32.models.Infrastructure.DataCentre.Node.StorageUtil\x1a\x80\x02\n\x03\x43pu\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\t\x12>\n\x05\x63ores\x18\x03 \x03(\x0b\x32/.models.Infrastructure.DataCentre.Node.Cpu.Core\x1a\x9e\x01\n\x04\x43ore\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12M\n\x0butilisation\x18\x01 \x03(\x0b\x32\x38.models.Infrastructure.DataCentre.Node.Cpu.Core.CoreUtil\x1a-\n\x08\x43oreUtil\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x13\n\x0butilisation\x18\x02 \x01(\x02\x1a\x33\n\nMemoryUtil\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x0b\n\x03ram\x18\x03 \x01(\x05\x1a\x38\n\x0bStorageUtil\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x0f\n\x07storage\x18\x03 \x01(\x05\x42\"\n\x13\x65u.recap.sim.modelsB\x0bUtilisationb\x06proto3')
)




_INFRASTRUCTURE_DATACENTRE_SWITCH_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='models.Infrastructure.DataCentre.Switch.Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Infrastructure.DataCentre.Switch.Link.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=374,
)

_INFRASTRUCTURE_DATACENTRE_SWITCH = _descriptor.Descriptor(
  name='Switch',
  full_name='models.Infrastructure.DataCentre.Switch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='links', full_name='models.Infrastructure.DataCentre.Switch.links', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFRASTRUCTURE_DATACENTRE_SWITCH_LINK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=374,
)

_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE_COREUTIL = _descriptor.Descriptor(
  name='CoreUtil',
  full_name='models.Infrastructure.DataCentre.Node.Cpu.Core.CoreUtil',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='models.Infrastructure.DataCentre.Node.Cpu.Core.CoreUtil.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utilisation', full_name='models.Infrastructure.DataCentre.Node.Cpu.Core.CoreUtil.utilisation', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=798,
  serialized_end=843,
)

_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE = _descriptor.Descriptor(
  name='Core',
  full_name='models.Infrastructure.DataCentre.Node.Cpu.Core',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='models.Infrastructure.DataCentre.Node.Cpu.Core.ID', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Infrastructure.DataCentre.Node.Cpu.Core.Name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utilisation', full_name='models.Infrastructure.DataCentre.Node.Cpu.Core.utilisation', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE_COREUTIL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=843,
)

_INFRASTRUCTURE_DATACENTRE_NODE_CPU = _descriptor.Descriptor(
  name='Cpu',
  full_name='models.Infrastructure.DataCentre.Node.Cpu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Infrastructure.DataCentre.Node.Cpu.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='models.Infrastructure.DataCentre.Node.Cpu.ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cores', full_name='models.Infrastructure.DataCentre.Node.Cpu.cores', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=843,
)

_INFRASTRUCTURE_DATACENTRE_NODE_MEMORYUTIL = _descriptor.Descriptor(
  name='MemoryUtil',
  full_name='models.Infrastructure.DataCentre.Node.MemoryUtil',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Infrastructure.DataCentre.Node.MemoryUtil.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='models.Infrastructure.DataCentre.Node.MemoryUtil.ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram', full_name='models.Infrastructure.DataCentre.Node.MemoryUtil.ram', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=845,
  serialized_end=896,
)

_INFRASTRUCTURE_DATACENTRE_NODE_STORAGEUTIL = _descriptor.Descriptor(
  name='StorageUtil',
  full_name='models.Infrastructure.DataCentre.Node.StorageUtil',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Infrastructure.DataCentre.Node.StorageUtil.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='models.Infrastructure.DataCentre.Node.StorageUtil.ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage', full_name='models.Infrastructure.DataCentre.Node.StorageUtil.storage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=898,
  serialized_end=954,
)

_INFRASTRUCTURE_DATACENTRE_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='models.Infrastructure.DataCentre.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='models.Infrastructure.DataCentre.Node.cpu', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memoryUtil', full_name='models.Infrastructure.DataCentre.Node.memoryUtil', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storageUtil', full_name='models.Infrastructure.DataCentre.Node.storageUtil', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFRASTRUCTURE_DATACENTRE_NODE_CPU, _INFRASTRUCTURE_DATACENTRE_NODE_MEMORYUTIL, _INFRASTRUCTURE_DATACENTRE_NODE_STORAGEUTIL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=954,
)

_INFRASTRUCTURE_DATACENTRE = _descriptor.Descriptor(
  name='DataCentre',
  full_name='models.Infrastructure.DataCentre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='models.Infrastructure.DataCentre.Name', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='models.Infrastructure.DataCentre.ID', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='models.Infrastructure.DataCentre.nodes', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='switches', full_name='models.Infrastructure.DataCentre.switches', index=3,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFRASTRUCTURE_DATACENTRE_SWITCH, _INFRASTRUCTURE_DATACENTRE_NODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=954,
)

_INFRASTRUCTURE = _descriptor.Descriptor(
  name='Infrastructure',
  full_name='models.Infrastructure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ExperimentId', full_name='models.Infrastructure.ExperimentId', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataCentres', full_name='models.Infrastructure.dataCentres', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFRASTRUCTURE_DATACENTRE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=954,
)

_INFRASTRUCTURE_DATACENTRE_SWITCH_LINK.containing_type = _INFRASTRUCTURE_DATACENTRE_SWITCH
_INFRASTRUCTURE_DATACENTRE_SWITCH.fields_by_name['links'].message_type = _INFRASTRUCTURE_DATACENTRE_SWITCH_LINK
_INFRASTRUCTURE_DATACENTRE_SWITCH.containing_type = _INFRASTRUCTURE_DATACENTRE
_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE_COREUTIL.containing_type = _INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE
_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE.fields_by_name['utilisation'].message_type = _INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE_COREUTIL
_INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE.containing_type = _INFRASTRUCTURE_DATACENTRE_NODE_CPU
_INFRASTRUCTURE_DATACENTRE_NODE_CPU.fields_by_name['cores'].message_type = _INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE
_INFRASTRUCTURE_DATACENTRE_NODE_CPU.containing_type = _INFRASTRUCTURE_DATACENTRE_NODE
_INFRASTRUCTURE_DATACENTRE_NODE_MEMORYUTIL.containing_type = _INFRASTRUCTURE_DATACENTRE_NODE
_INFRASTRUCTURE_DATACENTRE_NODE_STORAGEUTIL.containing_type = _INFRASTRUCTURE_DATACENTRE_NODE
_INFRASTRUCTURE_DATACENTRE_NODE.fields_by_name['cpu'].message_type = _INFRASTRUCTURE_DATACENTRE_NODE_CPU
_INFRASTRUCTURE_DATACENTRE_NODE.fields_by_name['memoryUtil'].message_type = _INFRASTRUCTURE_DATACENTRE_NODE_MEMORYUTIL
_INFRASTRUCTURE_DATACENTRE_NODE.fields_by_name['storageUtil'].message_type = _INFRASTRUCTURE_DATACENTRE_NODE_STORAGEUTIL
_INFRASTRUCTURE_DATACENTRE_NODE.containing_type = _INFRASTRUCTURE_DATACENTRE
_INFRASTRUCTURE_DATACENTRE.fields_by_name['nodes'].message_type = _INFRASTRUCTURE_DATACENTRE_NODE
_INFRASTRUCTURE_DATACENTRE.fields_by_name['switches'].message_type = _INFRASTRUCTURE_DATACENTRE_SWITCH
_INFRASTRUCTURE_DATACENTRE.containing_type = _INFRASTRUCTURE
_INFRASTRUCTURE.fields_by_name['dataCentres'].message_type = _INFRASTRUCTURE_DATACENTRE
DESCRIPTOR.message_types_by_name['Infrastructure'] = _INFRASTRUCTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Infrastructure = _reflection.GeneratedProtocolMessageType('Infrastructure', (_message.Message,), dict(

  DataCentre = _reflection.GeneratedProtocolMessageType('DataCentre', (_message.Message,), dict(

    Switch = _reflection.GeneratedProtocolMessageType('Switch', (_message.Message,), dict(

      Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
        DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_SWITCH_LINK,
        __module__ = 'Utilisation_pb2'
        # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Switch.Link)
        ))
      ,
      DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_SWITCH,
      __module__ = 'Utilisation_pb2'
      # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Switch)
      ))
    ,

    Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(

      Cpu = _reflection.GeneratedProtocolMessageType('Cpu', (_message.Message,), dict(

        Core = _reflection.GeneratedProtocolMessageType('Core', (_message.Message,), dict(

          CoreUtil = _reflection.GeneratedProtocolMessageType('CoreUtil', (_message.Message,), dict(
            DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE_COREUTIL,
            __module__ = 'Utilisation_pb2'
            # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Node.Cpu.Core.CoreUtil)
            ))
          ,
          DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_NODE_CPU_CORE,
          __module__ = 'Utilisation_pb2'
          # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Node.Cpu.Core)
          ))
        ,
        DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_NODE_CPU,
        __module__ = 'Utilisation_pb2'
        # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Node.Cpu)
        ))
      ,

      MemoryUtil = _reflection.GeneratedProtocolMessageType('MemoryUtil', (_message.Message,), dict(
        DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_NODE_MEMORYUTIL,
        __module__ = 'Utilisation_pb2'
        # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Node.MemoryUtil)
        ))
      ,

      StorageUtil = _reflection.GeneratedProtocolMessageType('StorageUtil', (_message.Message,), dict(
        DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_NODE_STORAGEUTIL,
        __module__ = 'Utilisation_pb2'
        # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Node.StorageUtil)
        ))
      ,
      DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE_NODE,
      __module__ = 'Utilisation_pb2'
      # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre.Node)
      ))
    ,
    DESCRIPTOR = _INFRASTRUCTURE_DATACENTRE,
    __module__ = 'Utilisation_pb2'
    # @@protoc_insertion_point(class_scope:models.Infrastructure.DataCentre)
    ))
  ,
  DESCRIPTOR = _INFRASTRUCTURE,
  __module__ = 'Utilisation_pb2'
  # @@protoc_insertion_point(class_scope:models.Infrastructure)
  ))
_sym_db.RegisterMessage(Infrastructure)
_sym_db.RegisterMessage(Infrastructure.DataCentre)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Switch)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Switch.Link)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Node)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Node.Cpu)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Node.Cpu.Core)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Node.Cpu.Core.CoreUtil)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Node.MemoryUtil)
_sym_db.RegisterMessage(Infrastructure.DataCentre.Node.StorageUtil)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
