# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkloadModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LocationModel_pb2 as LocationModel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorkloadModel.proto',
  package='models',
  syntax='proto3',
  serialized_options=_b('\n\023eu.recap.sim.modelsB\rWorkloadModel'),
  serialized_pb=_b('\n\x13WorkloadModel.proto\x12\x06models\x1a\x13LocationModel.proto\":\n\x08Workload\x12\x1f\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0e.models.Device\x12\r\n\x05notes\x18\x02 \x01(\t\"v\n\x06\x44\x65vice\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\t\x12\x12\n\ndeviceName\x18\x04 \x01(\t\x12#\n\tlocations\x18\x02 \x03(\x0b\x32\x10.models.Location\x12!\n\x08requests\x18\x01 \x03(\x0b\x32\x0f.models.Request\"\xa7\x01\n\x07Request\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x15\n\rapplicationId\x18\x02 \x01(\t\x12\x13\n\x0b\x63omponentId\x18\x03 \x01(\t\x12\r\n\x05\x61piId\x18\x04 \x01(\t\x12\x16\n\x0e\x64\x61taToTransfer\x18\x06 \x01(\x03\x12\x15\n\rmipsDataNodes\x18\x05 \x01(\x05\x12\x11\n\trequestId\x18\x07 \x01(\x05\x12\x11\n\tdataNodes\x18\x08 \x03(\x05\x42$\n\x13\x65u.recap.sim.modelsB\rWorkloadModelb\x06proto3')
  ,
  dependencies=[LocationModel__pb2.DESCRIPTOR,])




_WORKLOAD = _descriptor.Descriptor(
  name='Workload',
  full_name='models.Workload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='models.Workload.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='models.Workload.notes', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=110,
)


_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='models.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='models.Device.deviceId', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='models.Device.deviceName', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locations', full_name='models.Device.locations', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='models.Device.requests', index=3,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=230,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='models.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='models.Request.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applicationId', full_name='models.Request.applicationId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='componentId', full_name='models.Request.componentId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apiId', full_name='models.Request.apiId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataToTransfer', full_name='models.Request.dataToTransfer', index=4,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mipsDataNodes', full_name='models.Request.mipsDataNodes', index=5,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='models.Request.requestId', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataNodes', full_name='models.Request.dataNodes', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=400,
)

_WORKLOAD.fields_by_name['devices'].message_type = _DEVICE
_DEVICE.fields_by_name['locations'].message_type = LocationModel__pb2._LOCATION
_DEVICE.fields_by_name['requests'].message_type = _REQUEST
DESCRIPTOR.message_types_by_name['Workload'] = _WORKLOAD
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Workload = _reflection.GeneratedProtocolMessageType('Workload', (_message.Message,), dict(
  DESCRIPTOR = _WORKLOAD,
  __module__ = 'WorkloadModel_pb2'
  # @@protoc_insertion_point(class_scope:models.Workload)
  ))
_sym_db.RegisterMessage(Workload)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'WorkloadModel_pb2'
  # @@protoc_insertion_point(class_scope:models.Device)
  ))
_sym_db.RegisterMessage(Device)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'WorkloadModel_pb2'
  # @@protoc_insertion_point(class_scope:models.Request)
  ))
_sym_db.RegisterMessage(Request)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
